SYNTAX_TAG_RULES = {
    "함수 정의": {
        "category": "함수",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "클래스 정의": {
        "category": "객체지향",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "구조 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "if문": {
        "category": "조건문",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "for문": {
        "category": "반복문",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "while문": {
        "category": "반복문",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "return문": {
        "category": "함수",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "import문": {
        "category": "모듈",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "변수 할당": {
        "category": "변수",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "복합 할당": {
        "category": "변수",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "간결 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "함수 호출": {
        "category": "함수",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "비교 연산": {
        "category": "조건문",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "논리 연산": {
        "category": "조건문",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "조건 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "break문": {
        "category": "반복문",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "흐름 제어",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "continue문": {
        "category": "반복문",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "흐름 제어",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "예외 처리": {
        "category": "예외 처리",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "구조 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "raise문": {
        "category": "예외 처리",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "방어 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "assert문": {
        "category": "검증",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "방어 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "with문": {
        "category": "자원 관리",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "구조 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "lambda식": {
        "category": "함수",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "간결 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": False,
    },
    "리스트 컴프리헨션": {
        "category": "리스트",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "간결 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "딕셔너리 컴프리헨션": {
        "category": "딕셔너리",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "간결 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "세트 컴프리헨션": {
        "category": "세트",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "간결 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "제너레이터 표현식": {
        "category": "제너레이터",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "간결 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": False,
    },
    "리스트 리터럴": {
        "category": "자료구조",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "딕셔너리 리터럴": {
        "category": "자료구조",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "튜플 리터럴": {
        "category": "자료구조",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "인덱싱 사용": {
        "category": "자료 접근",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "속성 접근": {
        "category": "객체지향",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "구조 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "패턴 매칭": {
        "category": "조건문",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "구조 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "데코레이터 사용": {
        "category": "함수",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "고급 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "문자열 리터럴": {
        "category": "값",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "숫자 리터럴": {
        "category": "값",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "불리언 리터럴": {
        "category": "값",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "None 사용": {
        "category": "값",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "산술 연산": {
        "category": "연산",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "멤버십 연산": {
        "category": "조건문",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "조건 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "식별 비교": {
        "category": "조건문",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "조건 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "삼항 조건식": {
        "category": "조건문",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "간결 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": False,
    },
    "슬라이싱 사용": {
        "category": "자료 접근",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "자료 접근 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "위치 인자 사용": {
        "category": "함수",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "키워드 인자 사용": {
        "category": "함수",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "명시적 호출 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "기본 매개변수": {
        "category": "함수",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "함수 설계 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "가변 인자 사용": {
        "category": "함수",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "고급 함수 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "키워드 가변 인자 사용": {
        "category": "함수",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "고급 함수 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "타입 힌트 사용": {
        "category": "타입",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "명시적 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "f-string 사용": {
        "category": "문자열",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "문자열 처리 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "print 사용": {
        "category": "입출력",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "출력 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "input 사용": {
        "category": "입출력",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "입력 문법",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "len 사용": {
        "category": "내장 함수",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 내장 함수",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "range 사용": {
        "category": "내장 함수",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "기본 내장 함수",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "sum 사용": {
        "category": "내장 함수",
        "grammar_level": "하위 문법",
        "difficulty": "쉬운 문법",
        "style_role": "집계 내장 함수",
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "sorted 사용": {
        "category": "내장 함수",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "정렬 내장 함수",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "enumerate 사용": {
        "category": "내장 함수",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "반복 보조 함수",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "zip 사용": {
        "category": "내장 함수",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "반복 보조 함수",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "open 사용": {
        "category": "입출력",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "파일 입출력 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "문자열 메서드 호출": {
        "category": "문자열",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "문자열 처리 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "리스트 메서드 호출": {
        "category": "리스트",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "자료구조 처리 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "딕셔너리 메서드 호출": {
        "category": "딕셔너리",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "자료구조 처리 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "전역 변수 사용": {
        "category": "변수",
        "grammar_level": "상위 문법",
        "difficulty": "중간 문법",
        "style_role": "상태 관리 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": False,
    },
    "비동기 함수 정의": {
        "category": "비동기",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "비동기 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "await 사용": {
        "category": "비동기",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "비동기 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
}


CONCEPT_TAG_RULES = {
    "함수 중심 코드 구조": {
        "category": "함수",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "구조 생성",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "클래스 중심 코드 구조": {
        "category": "객체지향",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "구조 생성",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "절차형 코드 스타일": {
        "category": "절차형",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "실행 흐름 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": False,
    },
    "조건문 중심 구조": {
        "category": "조건문",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "구조 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "반복문 중심 구조": {
        "category": "반복문",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "구조 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "인덱스 기반 반복 사용": {
        "category": "반복문",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "반복 방식 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "직접 반복 사용": {
        "category": "반복문",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "반복 방식 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "리스트 누적 방식 사용": {
        "category": "리스트",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "데이터 누적 방식 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "컴프리헨션 기반 간결 구조": {
        "category": "컴프리헨션",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "간결성 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "조건문 중첩 구조": {
        "category": "조건문",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "복잡도 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "깊은 중첩 구조": {
        "category": "조건문",
        "concept_level": "복잡 구조",
        "difficulty": "어려운 구조",
        "style_role": "복잡도 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": False,
    },
    "예외 처리 포함 구조": {
        "category": "예외 처리",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "안정성 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "파일/자원 관리 구조": {
        "category": "자원 관리",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "안정성 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "반환 중심 구조": {
        "category": "함수",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "함수 흐름 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "데이터 컬렉션 중심 구조": {
        "category": "자료구조",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "데이터 처리 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "함수 호출 중심 구조": {
        "category": "함수",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "실행 흐름 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "상태 변경 중심 구조": {
        "category": "변수",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "상태 변화 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "모듈 의존 구조": {
        "category": "모듈",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "의존성 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "객체 접근 중심 구조": {
        "category": "객체지향",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "객체 사용 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "인덱싱 중심 구조": {
        "category": "자료 접근",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "자료 접근 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "복잡한 조건식 사용": {
        "category": "조건문",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "조건 복잡도 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "방어적 프로그래밍 구조": {
        "category": "검증",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "안정성 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "패턴 매칭 구조": {
        "category": "조건문",
        "concept_level": "복잡 구조",
        "difficulty": "어려운 구조",
        "style_role": "구조 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "간결성 저하 가능 구조": {
        "category": "복잡도",
        "concept_level": "복잡 구조",
        "difficulty": "어려운 구조",
        "style_role": "간결성 판단",
        "concise_limit_count": 1,
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "구조화 필요 코드": {
        "category": "구조화",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "개선 필요성 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "입출력 중심 코드": {
        "category": "입출력",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "입출력 흐름 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "데이터 필터링 구조": {
        "category": "데이터 처리",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "필터링 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "데이터 변환 구조": {
        "category": "데이터 처리",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "변환 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "데이터 집계 구조": {
        "category": "데이터 처리",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "집계 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "검색/탐색 중심 구조": {
        "category": "탐색",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "탐색 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "정렬 중심 구조": {
        "category": "정렬",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "정렬 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "검증 로직 중심 구조": {
        "category": "검증",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "검증 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "문자열 처리 중심 구조": {
        "category": "문자열",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "문자열 처리 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "딕셔너리 기반 매핑 구조": {
        "category": "딕셔너리",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "매핑 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "반복 인덱스 개선 가능 구조": {
        "category": "반복문",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "개선 가능성 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "함수 매개변수 활용 구조": {
        "category": "함수",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "함수 설계 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "타입 명시 코드 구조": {
        "category": "타입",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "명시성 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "내장 함수 활용 구조": {
        "category": "내장 함수",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "내장 함수 활용 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "사용자 입력 처리 구조": {
        "category": "입출력",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "입력 처리 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "파일 입출력 구조": {
        "category": "파일 입출력",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "파일 처리 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": False,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "비동기 처리 구조": {
        "category": "비동기",
        "concept_level": "복잡 구조",
        "difficulty": "어려운 구조",
        "style_role": "비동기 흐름 판단",
        "concise_limit_count": 1,
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "중복 로직 포함 구조": {
        "category": "중복",
        "concept_level": "중간 구조",
        "difficulty": "중간 구조",
        "style_role": "리팩토링 필요성 판단",
        "concise_limit_count": 2,
        "allowed_in_beginner": True,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "단일 책임 함수 구조": {
        "category": "함수",
        "concept_level": "기본 구조",
        "difficulty": "쉬운 구조",
        "style_role": "함수 책임 판단",
        "concise_limit_count": 3,
        "allowed_in_beginner": True,
        "allowed_in_concise": True,
        "allowed_in_structured": True,
    },
    "긴 함수 구조": {
        "category": "함수",
        "concept_level": "복잡 구조",
        "difficulty": "어려운 구조",
        "style_role": "리팩토링 필요성 판단",
        "concise_limit_count": 1,
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": True,
    },
    "전역 상태 의존 구조": {
        "category": "상태 관리",
        "concept_level": "복잡 구조",
        "difficulty": "어려운 구조",
        "style_role": "상태 의존성 판단",
        "concise_limit_count": 1,
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": False,
    },
}


def get_syntax_tag_rule(tag_name: str) -> dict:
    return SYNTAX_TAG_RULES.get(tag_name, {
        "category": "기타",
        "grammar_level": "상위 문법",
        "difficulty": "어려운 문법",
        "style_role": "미정의 문법",
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": False,
    })


def get_concept_tag_rule(tag_name: str) -> dict:
    return CONCEPT_TAG_RULES.get(tag_name, {
        "category": "기타",
        "concept_level": "복잡 구조",
        "difficulty": "어려운 구조",
        "style_role": "미정의 구조",
        "concise_limit_count": 1,
        "allowed_in_beginner": False,
        "allowed_in_concise": False,
        "allowed_in_structured": False,
    })


def enrich_syntax_tag(tag_item: dict) -> dict:
    tag_name = tag_item.get("tag", "")
    rule = get_syntax_tag_rule(tag_name)
    return {
        **tag_item,
        **rule,
    }


def enrich_concept_tag(tag_item: dict) -> dict:
    tag_name = tag_item.get("tag", "")
    rule = get_concept_tag_rule(tag_name)
    return {
        **tag_item,
        **rule,
    }